import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Storemate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Storemate
        </h1>

        <p className={styles.description}>
          Storemate helps you maintain your on IPFS based on chain assets
        </p>

        <div className={styles.grid}>
          <Link href="/view" legacyBehavior>
            <a className={styles.card}>
              <h2>View Assets&rarr;</h2>
              <p>Find in-depth information about all your assets that feature IPFS resources.</p>
            </a>
          </Link>

          <a href="/follow" className={styles.card}>
            <h2>Subscribe&rarr;</h2>
            <p>Get detailed real time Push notifications if any of your asset's data is at risk</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ for ETHIndia
        </a>
      </footer>
    </div>
  )
}
